-- MySQL Workbench Synchronization
-- Generated: 2019-11-22 20:16
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: alu201720081

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `mydb`.`cliente` 
DROP COLUMN `Email`,
DROP COLUMN `Telefone`,
DROP COLUMN `Endereco`,
ADD COLUMN `idcliente` INT(11) NOT NULL AUTO_INCREMENT FIRST,
ADD COLUMN `dt_nascimento` DATETIME NOT NULL AFTER `nome`,
ADD COLUMN `rg` VARCHAR(10) NOT NULL AFTER `cpf`,
ADD COLUMN `tcelular` VARCHAR(15) NOT NULL AFTER `rg`,
ADD COLUMN `tfixo` VARCHAR(15) NULL DEFAULT NULL AFTER `tcelular`,
ADD COLUMN `rua` VARCHAR(45) NOT NULL AFTER `tfixo`,
ADD COLUMN `numero` INT(11) NOT NULL AFTER `rua`,
ADD COLUMN `bairro` VARCHAR(45) NOT NULL AFTER `numero`,
ADD COLUMN `cidade` VARCHAR(45) NOT NULL AFTER `bairro`,
ADD COLUMN `estado` VARCHAR(45) NOT NULL AFTER `cidade`,
ADD COLUMN `pais` VARCHAR(45) NOT NULL AFTER `estado`,
ADD COLUMN `status` TINYINT(4) NOT NULL AFTER `pais`,
CHANGE COLUMN `Nome` `nome` VARCHAR(45) NOT NULL AFTER `idcliente`,
CHANGE COLUMN `cpf` `cpf` VARCHAR(14) NOT NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`idcliente`);
;

DROP TABLE IF EXISTS `mydb`.`tipo` ;

DROP TABLE IF EXISTS `mydb`.`peca` ;

DROP TABLE IF EXISTS `mydb`.`lancamento` ;

DROP TABLE IF EXISTS `mydb`.`historico` ;

DROP TABLE IF EXISTS `mydb`.`fornecedor` ;

DROP TABLE IF EXISTS `mydb`.`empresa` ;

DROP TABLE IF EXISTS `mydb`.`categoria` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
